import { Category, Note, Profile, Review, SystemSettings, Withdrawal, Report, Notification, Purchase } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Computer Science', slug: 'computer-science', description: 'Data Structures, Algorithms, Web Dev, OS, DBMS, AI & ML handwritten notes', created_at: '2026-01-01T00:00:00Z', note_count: 42 },
  { id: 'cat-2', name: 'Information Technology', slug: 'information-technology', description: 'Cloud Computing, Cybersecurity, Software Engineering, DevOps notes', created_at: '2026-01-01T00:00:00Z', note_count: 28 },
  { id: 'cat-3', name: 'Mechanical Engineering', slug: 'mechanical-engineering', description: 'Thermodynamics, Fluid Mechanics, Theory of Machines, CAD notes', created_at: '2026-01-01T00:00:00Z', note_count: 19 },
  { id: 'cat-4', name: 'Civil Engineering', slug: 'civil-engineering', description: 'Structural Analysis, Surveying, Geotechnical, Environmental Engineering', created_at: '2026-01-01T00:00:00Z', note_count: 15 },
  { id: 'cat-5', name: 'Electrical Engineering', slug: 'electrical-engineering', description: 'Circuit Theory, Control Systems, Power Systems, Signals & Systems', created_at: '2026-01-01T00:00:00Z', note_count: 22 },
  { id: 'cat-6', name: 'Electronics & Comm', slug: 'electronics-comm', description: 'Digital Signal Processing, Embedded Systems, VLSI, Microprocessors', created_at: '2026-01-01T00:00:00Z', note_count: 31 },
  { id: 'cat-7', name: 'Management & MBA', slug: 'management-mba', description: 'Financial Accounting, Marketing Strategy, Human Resource Management', created_at: '2026-01-01T00:00:00Z', note_count: 14 },
  { id: 'cat-8', name: 'Mathematics', slug: 'mathematics', description: 'Calculus, Linear Algebra, Differential Equations, Discrete Mathematics', created_at: '2026-01-01T00:00:00Z', note_count: 38 },
  { id: 'cat-9', name: 'Physics', slug: 'physics', description: 'Quantum Mechanics, Electromagnetism, Optics, Classical Mechanics', created_at: '2026-01-01T00:00:00Z', note_count: 17 },
  { id: 'cat-10', name: 'Chemistry', slug: 'chemistry', description: 'Organic, Inorganic, Physical Chemistry & Spectroscopy notes', created_at: '2026-01-01T00:00:00Z', note_count: 16 },
  { id: 'cat-11', name: 'Biology & Biotech', slug: 'biology-biotech', description: 'Genetics, Biochemistry, Microbiology, Cell Biology notes', created_at: '2026-01-01T00:00:00Z', note_count: 11 },
  { id: 'cat-12', name: 'Commerce & CA', slug: 'commerce-ca', description: 'Corporate Accounting, Business Law, Taxation, Costing notes', created_at: '2026-01-01T00:00:00Z', note_count: 25 },
  { id: 'cat-13', name: 'Arts & Humanities', slug: 'arts-humanities', description: 'Psychology, Economics, History, Political Science notes', created_at: '2026-01-01T00:00:00Z', note_count: 9 },

  // GOVERNMENT & COMPETITIVE EXAM CATEGORIES
  { id: 'cat-gov-1', name: 'UPSC Civil Services (IAS/IPS)', slug: 'upsc-civil-services', description: 'UPSC CSE Prelims & Mains General Studies, History, Polity, Economy handwritten notes', created_at: '2026-01-01T00:00:00Z', note_count: 54 },
  { id: 'cat-gov-2', name: 'GATE Engineering Exam', slug: 'gate-exam', description: 'GATE CSE, ECE, EE, ME, CE branch-wise formulas, shortcuts & solved PYQs', created_at: '2026-01-01T00:00:00Z', note_count: 62 },
  { id: 'cat-gov-3', name: 'SSC CGL & CHSL Exams', slug: 'ssc-exams', description: 'Quantitative Aptitude, General Intelligence, Reasoning, English & GA notes', created_at: '2026-01-01T00:00:00Z', note_count: 48 },
  { id: 'cat-gov-4', name: 'Banking & Insurance (IBPS, SBI)', slug: 'banking-exams', description: 'Banking Awareness, Financial GK, Data Interpretation, Reasoning notes', created_at: '2026-01-01T00:00:00Z', note_count: 36 },
  { id: 'cat-gov-5', name: 'RRB Railway Exams (NTPC/JE)', slug: 'rrb-railway-exams', description: 'RRB NTPC, Group D, JE General Science, Mathematics & Technical notes', created_at: '2026-01-01T00:00:00Z', note_count: 29 },
  { id: 'cat-gov-6', name: 'JEE Main & Advanced', slug: 'jee-main-advanced', description: 'IIT JEE Physics, Chemistry, Mathematics mindmaps, formulas & trick notes', created_at: '2026-01-01T00:00:00Z', note_count: 75 },
  { id: 'cat-gov-7', name: 'NEET UG Medical Exam', slug: 'neet-ug-medical', description: 'NCERT Biology line-by-line notes, Chemistry mechanisms & Physics numericals', created_at: '2026-01-01T00:00:00Z', note_count: 68 },
  { id: 'cat-gov-8', name: 'CAT, XAT & MBA Entrances', slug: 'cat-mba-entrances', description: 'VARC, DILR, Quantitative Ability shortcuts & MBA entrance strategy notes', created_at: '2026-01-01T00:00:00Z', note_count: 24 },
  { id: 'cat-gov-9', name: 'State PSC & Govt Exams', slug: 'state-psc-exams', description: 'State Public Service Commission (MPSC, UPPSC, BPSC, KPSC, TNPSC) notes', created_at: '2026-01-01T00:00:00Z', note_count: 33 },
  { id: 'cat-gov-10', name: 'Defence Exams (NDA, CDS, AFCAT)', slug: 'defence-exams', description: 'NDA, CDS, AFCAT Mathematics, General Knowledge & SSB interview prep notes', created_at: '2026-01-01T00:00:00Z', note_count: 21 },
  { id: 'cat-gov-11', name: 'UGC NET & SET Exams', slug: 'ugc-net-set', description: 'Teaching & Research Aptitude (Paper 1) and Subject Paper 2 notes', created_at: '2026-01-01T00:00:00Z', note_count: 18 },

  // SCHOOL EDUCATION (CLASSES 10, 11, 12)
  { id: 'cat-school-10', name: 'Class 10th (CBSE / ICSE / State)', slug: 'class-10th-boards', description: 'Class 10th Maths, Science, Social Science, English & Hindi handwritten notes & PYQs', created_at: '2026-01-01T00:00:00Z', note_count: 46 },
  { id: 'cat-school-11-sci', name: 'Class 11th & 12th Science (PCM/PCB)', slug: 'class-11th-12th-science', description: 'Class 11 & 12 Physics, Chemistry, Mathematics & Biology handwritten NCERT notes & formulas', created_at: '2026-01-01T00:00:00Z', note_count: 58 },
  { id: 'cat-school-11-comm', name: 'Class 11th & 12th Commerce', slug: 'class-11th-12th-commerce', description: 'Class 11 & 12 Accountancy, Business Studies, Economics & Applied Maths notes', created_at: '2026-01-01T00:00:00Z', note_count: 34 },
  { id: 'cat-school-11-arts', name: 'Class 11th & 12th Arts & Humanities', slug: 'class-11th-12th-arts', description: 'Class 11 & 12 History, Political Science, Geography, Sociology & Psychology notes', created_at: '2026-01-01T00:00:00Z', note_count: 27 },

  // COMPLETE ENGLISH LITERATURE & LANGUAGE (SCHOOL TO PG)
  { id: 'cat-eng-complete', name: 'English Complete (Class 10-12, BA & MA)', slug: 'english-complete', description: 'Complete English notes: Class 10/11/12 literature & grammar, B.A. English Hons & M.A. English Literature', created_at: '2026-01-01T00:00:00Z', note_count: 65 },

  // GRADUATION / UNDERGRADUATE (UG) DEGREES
  { id: 'cat-ba', name: 'B.A. Arts & Humanities', slug: 'ba-arts-humanities', description: 'B.A. Political Science, History, Economics, Sociology, Psychology, Hindi & Philosophy notes', created_at: '2026-01-01T00:00:00Z', note_count: 52 },
  { id: 'cat-bsc', name: 'B.Sc. Science & Biotech', slug: 'bsc-science-biotech', description: 'B.Sc. Mathematics, Physics, Chemistry, Botany, Zoology, Biotech & Statistics notes', created_at: '2026-01-01T00:00:00Z', note_count: 49 },
  { id: 'cat-bcom', name: 'B.Com Commerce & Finance', slug: 'bcom-commerce-finance', description: 'B.Com Financial Accounting, Business Law, Corporate Tax, Auditing & Cost Accounting', created_at: '2026-01-01T00:00:00Z', note_count: 44 },
  { id: 'cat-bca', name: 'BCA & Computer Applications', slug: 'bca-computer-applications', description: 'BCA C++, Java, Python, Web Development, DBMS, OS, Data Structures & Networking', created_at: '2026-01-01T00:00:00Z', note_count: 38 },
  { id: 'cat-bba', name: 'BBA & Business Management', slug: 'bba-business-management', description: 'BBA Principles of Management, Marketing, Finance, HR, Business Law & Entrepreneurship', created_at: '2026-01-01T00:00:00Z', note_count: 31 },
  { id: 'cat-law', name: 'Law (LL.B. & LL.M.)', slug: 'law-llb-llm', description: 'Constitutional Law, IPC/BNS, CrPC, Contract Law, Jurisprudence, Torts & Corporate Law', created_at: '2026-01-01T00:00:00Z', note_count: 36 },
  { id: 'cat-bed', name: 'Education & Teaching (B.Ed. & M.Ed.)', slug: 'education-bed-med', description: 'B.Ed. & M.Ed. Childhood Development, Learning & Teaching, Pedagogy of School Subjects', created_at: '2026-01-01T00:00:00Z', note_count: 22 },

  // POST GRADUATION (PG / MASTERS) DEGREES
  { id: 'cat-ma', name: 'M.A. Masters in Arts', slug: 'ma-masters-arts', description: 'M.A. Political Science, History, Economics, Sociology, Psychology & Hindi Literature', created_at: '2026-01-01T00:00:00Z', note_count: 39 },
  { id: 'cat-msc', name: 'M.Sc. Masters in Science', slug: 'msc-masters-science', description: 'M.Sc. Physics, Chemistry, Mathematics, Biotech, Botany, Zoology & Data Science notes', created_at: '2026-01-01T00:00:00Z', note_count: 37 },
  { id: 'cat-mcom', name: 'M.Com Masters in Commerce', slug: 'mcom-masters-commerce', description: 'M.Com Advanced Corporate Accounting, Financial Management, Tax Planning & Strategic Management', created_at: '2026-01-01T00:00:00Z', note_count: 26 },
  { id: 'cat-mba', name: 'MBA & PGDM Management', slug: 'mba-management', description: 'MBA Marketing Strategy, Corporate Finance, HRM, Supply Chain, Operations & Business Analytics', created_at: '2026-01-01T00:00:00Z', note_count: 48 },

  { id: 'cat-14', name: 'Other / Custom Domains', slug: 'other-domains', description: 'General aptitude, competitive exam prep, notes from other custom categories', created_at: '2026-01-01T00:00:00Z', note_count: 8 }
];

export const MOCK_USERS: Profile[] = [
  {
    id: 'user-seller-1',
    full_name: 'Aarav Sharma',
    email: 'aarav.sharma@iitb.ac.in',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    college: 'Department of Computer Science',
    university: 'IIT Bombay',
    course: 'B.Tech CS',
    semester: '6th Semester',
    role: 'seller',
    bio: 'CS student at IIT Bombay. Top 1% in GATE CSE & UPSC Prelims. Sharing neat handwritten notes with diagrammatic explanations and solved PYQs.',
    created_at: '2025-08-10T00:00:00Z',
    updated_at: '2026-01-10T00:00:00Z'
  },
  {
    id: 'user-seller-2',
    full_name: 'Priya Patel',
    email: 'priya.p@dtu.ac.in',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
    college: 'Delhi Technological University',
    university: 'DTU Delhi',
    course: 'B.Tech IT',
    semester: '4th Semester',
    role: 'seller',
    bio: 'Passionate note-maker & topper at DTU. Clear handwriting with colored callouts and step-by-step algorithms.',
    created_at: '2025-09-15T00:00:00Z',
    updated_at: '2026-01-12T00:00:00Z'
  },
  {
    id: 'user-student-1',
    full_name: 'Rohan Gupta',
    email: 'rohan.gupta@gmail.com',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    college: 'College of Engineering Pune',
    university: 'COEP Pune',
    course: 'B.Tech Mechanical',
    semester: '3rd Semester',
    role: 'student',
    bio: 'Eager learner looking for quality notes to ace university semester exams & government competitive exams.',
    created_at: '2026-01-05T00:00:00Z',
    updated_at: '2026-01-05T00:00:00Z'
  },
  {
    id: 'user-admin-1',
    full_name: 'NoteMart Platform Admin',
    email: 'admin@notemart.edu',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    university: 'NoteMart Central HQ',
    role: 'admin',
    bio: 'Official NoteMart System Administrator & Content Moderation Lead.',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z'
  }
];

export const MOCK_NOTES: Note[] = [
  {
    id: 'note-1',
    seller_id: 'user-seller-1',
    category_id: 'cat-1',
    title: 'Data Structures & Algorithms Complete Master Class Notes',
    slug: 'data-structures-algorithms-complete-master-class-notes',
    description: 'Comprehensive 142-page handwritten notes covering Arrays, Linked Lists, Stacks, Queues, Trees (AVL, Red-Black), Graphs, Sorting Algorithms, Dynamic Programming, and Greedy Methods. Includes memory visualization diagrams, time/space complexity analysis table, and 50+ solved semester examination questions.',
    subject: 'Data Structures',
    university: 'IIT Bombay',
    college: 'Department of CS',
    course: 'B.Tech Computer Science',
    semester: '3rd Semester',
    year: '2025-2026',
    language: 'English',
    tags: ['DSA', 'Arrays', 'Trees', 'Graphs', 'Dynamic Programming', 'IIT Bombay', 'GATE'],
    pdf_path: '/sample-notes/dsa-notes.pdf',
    preview_path: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800',
    thumbnail_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=600',
    file_size: 14200000,
    page_count: 142,
    price: 49,
    is_free: false,
    status: 'approved',
    downloads: 1420,
    views: 4850,
    average_rating: 4.9,
    rating_count: 128,
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-01-10T10:00:00Z',
    seller: MOCK_USERS[0],
    category: INITIAL_CATEGORIES[0]
  },
  {
    id: 'note-gov-1',
    seller_id: 'user-seller-1',
    category_id: 'cat-gov-1',
    title: 'UPSC CSE Indian Polity & Constitution Mind Maps & Article Cheatsheet',
    slug: 'upsc-cse-indian-polity-constitution-mind-maps',
    description: 'Complete 180-page handwritten notes for UPSC CSE Prelims & Mains General Studies Paper II. Covers Fundamental Rights, DPSP, Parliament, Judiciary, Constitutional Bodies, Landmark Supreme Court Judgments, and 10-year solved PYQ breakdowns.',
    subject: 'Indian Polity',
    university: 'UPSC Exam Prep',
    college: 'Vajiram Alumni Notes',
    course: 'UPSC Civil Services',
    semester: 'Competitive Exam',
    year: '2026',
    language: 'English',
    tags: ['UPSC', 'IAS', 'Polity', 'Laxmikanth', 'Constitution', 'General Studies'],
    pdf_path: '/sample-notes/upsc-polity.pdf',
    preview_path: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=800',
    thumbnail_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=600',
    file_size: 18500000,
    page_count: 180,
    price: 99,
    is_free: false,
    status: 'approved',
    downloads: 2840,
    views: 9200,
    average_rating: 4.95,
    rating_count: 215,
    created_at: '2026-01-12T08:00:00Z',
    updated_at: '2026-01-12T08:00:00Z',
    seller: MOCK_USERS[0],
    category: INITIAL_CATEGORIES[13]
  },
  {
    id: 'note-2',
    seller_id: 'user-seller-2',
    category_id: 'cat-1',
    title: 'Operating Systems & Process Synchronization Hand-Crafted Notes',
    slug: 'operating-systems-process-synchronization-notes',
    description: 'Neatly organized notes on Process Scheduling, Semaphore, Deadlocks, Virtual Memory Management, Paging, Segmentation, and File Systems. Includes step-by-step Bankers Algorithm examples and Peterson solution breakdown.',
    subject: 'Operating Systems',
    university: 'DTU Delhi',
    college: 'Department of IT',
    course: 'B.Tech IT',
    semester: '4th Semester',
    year: '2025-2026',
    language: 'English',
    tags: ['Operating Systems', 'Process', 'Deadlock', 'Paging', 'DTU', 'Semaphores'],
    pdf_path: '/sample-notes/os-notes.pdf',
    preview_path: 'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&q=80&w=800',
    thumbnail_url: 'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&q=80&w=600',
    file_size: 9800000,
    page_count: 88,
    price: 0,
    is_free: true,
    status: 'approved',
    downloads: 2150,
    views: 6300,
    average_rating: 4.8,
    rating_count: 94,
    created_at: '2026-01-15T14:30:00Z',
    updated_at: '2026-01-15T14:30:00Z',
    seller: MOCK_USERS[1],
    category: INITIAL_CATEGORIES[0]
  },
  {
    id: 'note-10-eng',
    seller_id: 'user-seller-2',
    category_id: 'cat-eng-complete',
    title: 'Class 10th English Complete Master Notes (First Flight, Footprints & Grammar)',
    slug: 'class-10th-english-complete-master-notes',
    description: 'Comprehensive 120-page handwritten notes for Class 10 CBSE/State Board English. Covers all chapter summaries, poetic devices, character sketches for First Flight and Footprints Without Feet, along with Formal Letter, Analytical Paragraph writing templates, and 100+ solved grammar questions (Tenses, Modals, Reported Speech).',
    subject: 'English Complete (First Flight & Footprints)',
    university: 'CBSE Board Examination',
    college: 'Delhi Public School Alumni',
    course: 'Class 10th (CBSE / NCERT)',
    semester: 'Full Syllabus (Board Exam)',
    year: '2025-2026',
    language: 'English',
    tags: ['Class 10', 'English', 'CBSE', 'First Flight', 'Grammar', 'Board Exam', 'Literature'],
    pdf_path: '/sample-notes/class-10-english.pdf',
    preview_path: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=800',
    thumbnail_url: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=600',
    file_size: 11200000,
    page_count: 120,
    price: 39,
    is_free: false,
    status: 'approved',
    downloads: 1890,
    views: 5400,
    average_rating: 4.92,
    rating_count: 142,
    created_at: '2026-01-18T09:00:00Z',
    updated_at: '2026-01-18T09:00:00Z',
    seller: MOCK_USERS[1],
    category: INITIAL_CATEGORIES.find((c) => c.slug === 'english-complete') || INITIAL_CATEGORIES[0]
  },
  {
    id: 'note-12-eng',
    seller_id: 'user-seller-1',
    category_id: 'cat-eng-complete',
    title: 'Class 12th English Core Complete Guide (Flamingo, Vistas & Writing Formats)',
    slug: 'class-12th-english-core-complete-guide',
    description: 'The ultimate 135-page Class 12 CBSE Board English Core notes. Line-by-line explanation of all Flamingo Prose & Poems (My Mother at Sixty-Six, Keeping Quiet, A Thing of Beauty) with themes, symbolism, NCERT questions, Vistas stories, and full-marks templates for Notice, Invitations & Replies, Letter to Editor, and Article/Report writing.',
    subject: 'English Core Complete (Flamingo, Vistas & Writing Skills)',
    university: 'CBSE Class 12 Board',
    college: 'Toppers Study Notes',
    course: 'Class 12th Science / Commerce / Arts',
    semester: 'Class 12 Boards (Full Syllabus)',
    year: '2025-2026',
    language: 'English',
    tags: ['Class 12', 'English Core', 'Flamingo', 'Vistas', 'Writing Skills', 'CBSE 12th'],
    pdf_path: '/sample-notes/class-12-english.pdf',
    preview_path: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800',
    thumbnail_url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600',
    file_size: 13800000,
    page_count: 135,
    price: 49,
    is_free: false,
    status: 'approved',
    downloads: 2430,
    views: 7100,
    average_rating: 4.96,
    rating_count: 184,
    created_at: '2026-01-20T11:00:00Z',
    updated_at: '2026-01-20T11:00:00Z',
    seller: MOCK_USERS[0],
    category: INITIAL_CATEGORIES.find((c) => c.slug === 'english-complete') || INITIAL_CATEGORIES[0]
  },
  {
    id: 'note-ba-eng-lit',
    seller_id: 'user-seller-2',
    category_id: 'cat-ba',
    title: 'B.A. (Hons) English Literature: Romantic Poetry, Shakespeare & Literary Criticism',
    slug: 'ba-hons-english-literature-romantic-poetry-criticism',
    description: 'Premium 165-page handwritten notes for B.A. English Honours (Delhi University / Calcutta University / Panjab University). Detailed textual analysis of Shakespearean tragedies (Hamlet, Macbeth), Wordsworth & Coleridge Lyrical Ballads, Keats Odes, Shelley, plus Aristotle Poetics, Philip Sidney, and T.S. Eliot Tradition and the Individual Talent.',
    subject: 'English Literature: British Romantic & Victorian Literature',
    university: 'University of Delhi (DU)',
    college: 'St. Stephen’s College Alumni',
    course: 'B.A. (Hons) English Literature',
    semester: '3rd Semester',
    year: '2025-2026',
    language: 'English',
    tags: ['B.A. English', 'English Honours', 'Shakespeare', 'Romanticism', 'Literary Criticism', 'Delhi University'],
    pdf_path: '/sample-notes/ba-english-literature.pdf',
    preview_path: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&q=80&w=800',
    thumbnail_url: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&q=80&w=600',
    file_size: 16200000,
    page_count: 165,
    price: 69,
    is_free: false,
    status: 'approved',
    downloads: 1670,
    views: 4890,
    average_rating: 4.88,
    rating_count: 112,
    created_at: '2026-01-22T13:00:00Z',
    updated_at: '2026-01-22T13:00:00Z',
    seller: MOCK_USERS[1],
    category: INITIAL_CATEGORIES.find((c) => c.slug === 'ba-arts-humanities') || INITIAL_CATEGORIES[0]
  },
  {
    id: 'note-bsc-maths',
    seller_id: 'user-seller-1',
    category_id: 'cat-bsc',
    title: 'B.Sc. Mathematics: Real Analysis, Group Theory & Multivariable Calculus',
    slug: 'bsc-mathematics-real-analysis-group-theory-calculus',
    description: 'Rigorous 150-page mathematical proofs and theorem notes for B.Sc. Mathematics. Complete proofs for Bolzano-Weierstrass theorem, Cauchy sequences, Riemann integration, Group Theory (Lagrange theorem, Normal Subgroups, Homomorphism), and Vector Calculus Green-Stokes theorems.',
    subject: 'B.Sc. Mathematics: Real Analysis, Abstract Algebra & Group Theory',
    university: 'BHU Varanasi',
    college: 'Faculty of Science',
    course: 'B.Sc. (Bachelor of Science)',
    semester: '4th Semester',
    year: '2025-2026',
    language: 'English',
    tags: ['B.Sc.', 'Mathematics', 'Real Analysis', 'Group Theory', 'Calculus', 'BHU'],
    pdf_path: '/sample-notes/bsc-math.pdf',
    preview_path: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=800',
    thumbnail_url: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=600',
    file_size: 15100000,
    page_count: 150,
    price: 59,
    is_free: false,
    status: 'approved',
    downloads: 1320,
    views: 3950,
    average_rating: 4.91,
    rating_count: 86,
    created_at: '2026-01-25T15:00:00Z',
    updated_at: '2026-01-25T15:00:00Z',
    seller: MOCK_USERS[0],
    category: INITIAL_CATEGORIES.find((c) => c.slug === 'bsc-science-biotech') || INITIAL_CATEGORIES[0]
  },
  {
    id: 'note-bcom-acc',
    seller_id: 'user-seller-2',
    category_id: 'cat-bcom',
    title: 'B.Com Financial Accounting & Corporate Law Complete Semester Notes',
    slug: 'bcom-financial-accounting-corporate-law-notes',
    description: 'Comprehensive 140-page notes for B.Com / B.Com (Hons). Covers AS & Ind AS standards, Branch & Departmental Accounting, Partnership dissolution, Issue & Forfeiture of Shares, Cash Flow Statements, along with Indian Companies Act 2013 provisions, MOA/AOA, and solved examination numericals.',
    subject: 'Financial Accounting & Accounting Standards',
    university: 'Shri Ram College of Commerce (SRCC)',
    college: 'Delhi University',
    course: 'B.Com (Bachelor of Commerce)',
    semester: '1st Year / 2nd Sem',
    year: '2025-2026',
    language: 'English',
    tags: ['B.Com', 'Accounting', 'Corporate Law', 'Financial Accounting', 'SRCC', 'DU'],
    pdf_path: '/sample-notes/bcom-accounting.pdf',
    preview_path: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=800',
    thumbnail_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=600',
    file_size: 14200000,
    page_count: 140,
    price: 49,
    is_free: false,
    status: 'approved',
    downloads: 1980,
    views: 5800,
    average_rating: 4.87,
    rating_count: 135,
    created_at: '2026-01-28T10:00:00Z',
    updated_at: '2026-01-28T10:00:00Z',
    seller: MOCK_USERS[1],
    category: INITIAL_CATEGORIES.find((c) => c.slug === 'bcom-commerce-finance') || INITIAL_CATEGORIES[0]
  },
  {
    id: 'note-ma-eng-lit',
    seller_id: 'user-seller-1',
    category_id: 'cat-ma',
    title: 'M.A. English Literature: Critical Theory, Modernism & Postcolonialism Notes',
    slug: 'ma-english-literature-critical-theory-modernism',
    description: 'Post-graduate level 175-page research-oriented handwritten notes. Deep dives into Structuralism (Saussure, Barthes), Post-structuralism & Deconstruction (Derrida, Foucault), Feminism, Edward Said Orientalism, Homi Bhabha Hybridity, T.S. Eliot The Waste Land, James Joyce Ulysses, and Virginia Woolf Mrs Dalloway.',
    subject: 'M.A. English: Literary Theory, Structuralism & Deconstruction',
    university: 'Jawaharlal Nehru University (JNU)',
    college: 'School of Language, Literature and Culture Studies',
    course: 'M.A. English Literature & Linguistics',
    semester: '2nd Semester (PG / Masters)',
    year: '2025-2026',
    language: 'English',
    tags: ['M.A. English', 'Critical Theory', 'Derrida', 'Postcolonialism', 'JNU', 'UGC NET English'],
    pdf_path: '/sample-notes/ma-english.pdf',
    preview_path: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&q=80&w=800',
    thumbnail_url: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&q=80&w=600',
    file_size: 17800000,
    page_count: 175,
    price: 89,
    is_free: false,
    status: 'approved',
    downloads: 1450,
    views: 4620,
    average_rating: 4.97,
    rating_count: 98,
    created_at: '2026-02-01T12:00:00Z',
    updated_at: '2026-02-01T12:00:00Z',
    seller: MOCK_USERS[0],
    category: INITIAL_CATEGORIES.find((c) => c.slug === 'english-complete') || INITIAL_CATEGORIES[0]
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    user_id: 'user-student-1',
    note_id: 'note-1',
    rating: 5,
    review: 'Hands down the best DSA notes I have read! The tree traversal diagrams and dynamic programming state transitions saved my semester exam. Worth every rupee.',
    created_at: '2026-01-12T14:22:00Z',
    user: MOCK_USERS[2]
  }
];

export const MOCK_PURCHASES: Purchase[] = [];

export const MOCK_WITHDRAWALS: Withdrawal[] = [
  {
    id: 'wth-1',
    seller_id: 'user-seller-1',
    amount: 1500,
    payment_method: 'upi',
    payment_details: 'aarav@okaxis',
    status: 'completed',
    admin_note: 'Payout processed via Razorpay Route transfer #TXN99281',
    created_at: '2026-02-01T10:00:00Z',
    processed_at: '2026-02-01T14:00:00Z',
    seller: MOCK_USERS[0]
  }
];

export const MOCK_REPORTS: Report[] = [
  {
    id: 'rep-1',
    reporter_id: 'user-student-1',
    note_id: 'note-3',
    reason: 'wrong_description',
    description: 'Page 45 has a typo in Laplace inverse formula.',
    status: 'pending',
    created_at: '2026-02-10T16:00:00Z',
    reporter: MOCK_USERS[2],
    note: MOCK_NOTES[2]
  }
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    user_id: 'user-seller-1',
    title: 'Note Approved 🎉',
    message: 'Your note "Data Structures & Algorithms Complete Master Class Notes" has been approved!',
    type: 'note_approved',
    is_read: false,
    created_at: '2026-01-10T10:05:00Z'
  }
];

export const DEFAULT_SYSTEM_SETTINGS: SystemSettings = {
  platform_commission: 25, // 25% PLATFORM COMMISSION (75% SELLER AMOUNT)
  gst_rate: 18,
  min_note_price: 0,
  max_note_price: 2000,
  min_withdrawal_amount: 100,
  max_pdf_size_mb: 2048,
  auto_approval: true,
  maintenance_mode: false,
  route_enabled: false,
  settlement_delay_days: 0,
  withdrawal_enabled: true,
  seller_registration_enabled: true,
  website_name: 'NoteMart',
  website_logo: '/logo.png',
  support_email: 'support@notemart.edu'
};

