const mongoose = require('mongoose');

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/notemart';

async function seed() {
  await mongoose.connect(MONGODB_URI);
  console.log('Connected to MongoDB for direct seeding');

  const UserSchema = new mongoose.Schema({
    name: String,
    email: { type: String, unique: true },
    password: { type: String, select: false },
    college: String,
    course: String,
    semester: String,
    profileImage: String,
    role: String,
    isEmailVerified: Boolean,
  }, { timestamps: true });

  const NoteSchema = new mongoose.Schema({
    seller: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    title: String,
    slug: { type: String, unique: true },
    description: String,
    subject: String,
    university: String,
    college: String,
    course: String,
    semester: String,
    year: String,
    language: String,
    tags: [String],
    price: Number,
    is_free: Boolean,
    pdf_path: String,
    storage_key: String,
    original_filename: String,
    mime_type: String,
    thumbnail_url: String,
    preview_path: String,
    file_size: Number,
    page_count: Number,
    status: String,
    downloads: Number,
    views: Number,
    average_rating: Number,
    rating_count: Number,
  }, { timestamps: true });

  const User = mongoose.models.User || mongoose.model('User', UserSchema);
  const Note = mongoose.models.Note || mongoose.model('Note', NoteSchema);

  const existingNotesCount = await Note.countDocuments();
  if (existingNotesCount > 0) {
    console.log(`MongoDB already has ${existingNotesCount} notes.`);
    process.exit(0);
  }

  // Create sellers
  const sellers = [
    {
      name: 'Rohan Sharma',
      email: 'rohan.aktu.topper@notemart.in',
      college: 'Institute of Engineering and Technology (IET Lucknow)',
      course: 'B.Tech Computer Science',
      semester: '5th Semester',
      role: 'seller',
      profileImage: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200',
    },
    {
      name: 'Priya Patel',
      email: 'priya.dtu.notes@notemart.in',
      college: 'Delhi Technological University (DTU)',
      course: 'B.Tech Information Technology',
      semester: '4th Semester',
      role: 'seller',
      profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    },
    {
      name: 'Aman Verma',
      email: 'aman.iitd@notemart.in',
      college: 'IIT Delhi',
      course: 'B.Tech Computer Science',
      semester: '6th Semester',
      role: 'seller',
      profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    },
    {
      name: 'Ananya Sen',
      email: 'ananya.upsc@notemart.in',
      college: 'St. Stephen\'s College, Delhi University',
      course: 'UPSC Civil Services Preparation',
      semester: 'Prelims + Mains',
      role: 'seller',
      profileImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200',
    },
  ];

  const sellerMap = {};
  for (const s of sellers) {
    let u = await User.findOne({ email: s.email });
    if (!u) {
      u = await User.create({
        ...s,
        password: '$2a$10$eO0K4G13tQo3z7y7j7wRfeQZ57QeK5b9.xL.Vw6YyJ3e.N2/nQdhe', // Valid bcrypt hash
        isEmailVerified: true,
      });
    }
    sellerMap[s.email] = u;
  }

  const notes = [
    {
      seller: sellerMap['rohan.aktu.topper@notemart.in']._id,
      title: 'Python Programming Notes',
      slug: 'python-programming-notes-aktu',
      description: 'Complete unit-wise handwritten notes for Python Programming according to the latest AKTU syllabus. Covers basic syntax, data structures, OOPs, modules, exception handling, and previous year university questions.',
      subject: 'Python Programming',
      university: 'Dr. A.P.J. Abdul Kalam Technical University (AKTU)',
      college: 'IET Lucknow',
      course: 'B.Tech CSE',
      semester: '3rd Semester',
      year: '2026',
      language: 'English',
      tags: ['python', 'programming', 'aktu', 'btech', 'cse', 'handwritten', 'notes'],
      price: 49,
      is_free: false,
      pdf_path: '/sample-notes/sample.pdf',
      storage_key: 'seed-python-prog',
      original_filename: 'python_programming_notes.pdf',
      mime_type: 'application/pdf',
      thumbnail_url: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&q=80&w=600',
      page_count: 95,
      file_size: 14850000,
      status: 'approved',
      downloads: 342,
      views: 1250,
      average_rating: 4.9,
      rating_count: 48,
    },
    {
      seller: sellerMap['rohan.aktu.topper@notemart.in']._id,
      title: 'Python Using AI Notes',
      slug: 'python-using-ai-notes-btech',
      description: 'Comprehensive guide and handwritten formula sheets for building AI and Machine Learning applications using Python. Covers OpenCV, Scikit-Learn, PyTorch basics, and end-to-end model workflows.',
      subject: 'Artificial Intelligence',
      university: 'Dr. A.P.J. Abdul Kalam Technical University (AKTU)',
      college: 'JSS Academy of Technical Education',
      course: 'B.Tech CSE (AI & ML)',
      semester: '5th Semester',
      year: '2026',
      language: 'English',
      tags: ['python', 'ai', 'artificial intelligence', 'machine learning', 'btech', 'aktu'],
      price: 79,
      is_free: false,
      pdf_path: '/sample-notes/sample.pdf',
      storage_key: 'seed-python-ai',
      original_filename: 'python_using_ai_notes.pdf',
      mime_type: 'application/pdf',
      thumbnail_url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=600',
      page_count: 115,
      file_size: 18450000,
      status: 'approved',
      downloads: 289,
      views: 980,
      average_rating: 4.8,
      rating_count: 36,
    },
    {
      seller: sellerMap['priya.dtu.notes@notemart.in']._id,
      title: 'Python Data Science Notes',
      slug: 'python-data-science-notes-dtu',
      description: 'Class topper notes on Python for Data Science. Includes clear explanations with code illustrations for NumPy, Pandas, Data Wrangling, Seaborn, Matplotlib, and statistical exploratory data analysis.',
      subject: 'Data Science',
      university: 'Delhi Technological University (DTU)',
      college: 'DTU Main Campus',
      course: 'B.Tech CSE',
      semester: '4th Semester',
      year: '2026',
      language: 'English',
      tags: ['python', 'data science', 'pandas', 'numpy', 'visualization', 'dtu'],
      price: 59,
      is_free: false,
      pdf_path: '/sample-notes/sample.pdf',
      storage_key: 'seed-python-ds',
      original_filename: 'python_data_science_notes.pdf',
      mime_type: 'application/pdf',
      thumbnail_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600',
      page_count: 88,
      file_size: 12600000,
      status: 'approved',
      downloads: 410,
      views: 1420,
      average_rating: 5.0,
      rating_count: 52,
    },
    {
      seller: sellerMap['rohan.aktu.topper@notemart.in']._id,
      title: 'Python B.Tech 3rd Year Notes',
      slug: 'python-btech-3rd-year-notes',
      description: 'Free revision notes and fast cheat sheets for Python Programming in B.Tech 3rd Year (5th Semester). Contains solved exam papers and key interview questions.',
      subject: 'Python Programming & Applications',
      university: 'Dr. A.P.J. Abdul Kalam Technical University (AKTU)',
      college: 'Galgotias College of Engineering',
      course: 'B.Tech CSE',
      semester: '5th Semester',
      year: '2026',
      language: 'English',
      tags: ['python', 'btech', '3rd year', 'aktu', 'free notes', 'quick revision'],
      price: 0,
      is_free: true,
      pdf_path: '/sample-notes/sample.pdf',
      storage_key: 'seed-python-free',
      original_filename: 'python_3rd_year_notes.pdf',
      mime_type: 'application/pdf',
      thumbnail_url: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=600',
      page_count: 72,
      file_size: 9400000,
      status: 'approved',
      downloads: 890,
      views: 2900,
      average_rating: 4.7,
      rating_count: 78,
    },
    {
      seller: sellerMap['rohan.aktu.topper@notemart.in']._id,
      title: 'Database Management System (DBMS) Notes',
      slug: 'database-management-system-dbms-notes-aktu',
      description: 'Complete Database Management System handwritten notes. Thorough coverage of ER Diagrams, Relational Algebra, SQL Queries, Normalization (1NF to BCNF), Transaction Processing, ACID properties, and Concurrency Control.',
      subject: 'DBMS',
      university: 'Dr. A.P.J. Abdul Kalam Technical University (AKTU)',
      college: 'ABES Engineering College',
      course: 'B.Tech CSE',
      semester: '4th Semester',
      year: '2026',
      language: 'English',
      tags: ['dbms', 'database', 'sql', 'normalization', 'transactions', 'aktu', 'cse'],
      price: 69,
      is_free: false,
      pdf_path: '/sample-notes/sample.pdf',
      storage_key: 'seed-dbms',
      original_filename: 'dbms_complete_handwritten.pdf',
      mime_type: 'application/pdf',
      thumbnail_url: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&q=80&w=600',
      page_count: 134,
      file_size: 21500000,
      status: 'approved',
      downloads: 512,
      views: 1800,
      average_rating: 4.9,
      rating_count: 64,
    },
    {
      seller: sellerMap['aman.iitd@notemart.in']._id,
      title: 'Operating System Complete Hand-Written Notes',
      slug: 'operating-system-complete-hand-written-notes',
      description: 'Top-scoring IIT Delhi lecture notes for Operating Systems. Detailed diagrams for Process Lifecycle, CPU Scheduling (FCFS, SJF, Round Robin), Deadlock Avoidance (Banker\'s Algorithm), Paging, Segmentation, and Virtual Memory.',
      subject: 'Operating System',
      university: 'IIT Delhi',
      college: 'Department of Computer Science, IIT Delhi',
      course: 'B.Tech CSE',
      semester: '4th Semester',
      year: '2026',
      language: 'English',
      tags: ['os', 'operating system', 'process scheduling', 'memory management', 'deadlocks', 'iit delhi'],
      price: 89,
      is_free: false,
      pdf_path: '/sample-notes/sample.pdf',
      storage_key: 'seed-os',
      original_filename: 'operating_system_notes.pdf',
      mime_type: 'application/pdf',
      thumbnail_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=600',
      page_count: 142,
      file_size: 23100000,
      status: 'approved',
      downloads: 460,
      views: 1650,
      average_rating: 5.0,
      rating_count: 59,
    },
    {
      seller: sellerMap['rohan.aktu.topper@notemart.in']._id,
      title: 'Computer Networks Full Handwritten Notes',
      slug: 'computer-networks-full-handwritten-notes',
      description: 'Crystal-clear notes covering the 7 layers of OSI and TCP/IP stack. Includes detailed numericals on IP addressing, Subnetting, CIDR, CRC checksum, Flow Control protocols, and Routing Algorithms (Dijkstra, Bellman-Ford).',
      subject: 'Computer Networks',
      university: 'Dr. A.P.J. Abdul Kalam Technical University (AKTU)',
      college: 'Ajay Kumar Garg Engineering College (AKGEC)',
      course: 'B.Tech CSE',
      semester: '5th Semester',
      year: '2026',
      language: 'English',
      tags: ['computer networks', 'cn', 'tcp/ip', 'osi model', 'routing', 'subnetting', 'aktu'],
      price: 59,
      is_free: false,
      pdf_path: '/sample-notes/sample.pdf',
      storage_key: 'seed-cn',
      original_filename: 'computer_networks_notes.pdf',
      mime_type: 'application/pdf',
      thumbnail_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=600',
      page_count: 110,
      file_size: 16200000,
      status: 'approved',
      downloads: 388,
      views: 1390,
      average_rating: 4.8,
      rating_count: 42,
    },
    {
      seller: sellerMap['priya.dtu.notes@notemart.in']._id,
      title: 'Data Structures & Algorithms (DSA) Topper Notes',
      slug: 'data-structures-and-algorithms-dsa-topper-notes',
      description: 'Comprehensive DSA notes curated by DTU coding club. Covers Arrays, Linked Lists, Stacks, Queues, Binary Trees, BST, AVL Trees, Heaps, Graph Traversals (BFS/DFS), Dynamic Programming, and Time Complexity analyses.',
      subject: 'Data Structures',
      university: 'Delhi Technological University (DTU)',
      college: 'DTU Delhi',
      course: 'B.Tech CSE',
      semester: '3rd Semester',
      year: '2026',
      language: 'English',
      tags: ['dsa', 'data structures', 'algorithms', 'trees', 'graphs', 'dynamic programming', 'dtu'],
      price: 99,
      is_free: false,
      pdf_path: '/sample-notes/sample.pdf',
      storage_key: 'seed-dsa',
      original_filename: 'dsa_topper_notes.pdf',
      mime_type: 'application/pdf',
      thumbnail_url: 'https://images.unsplash.com/photo-1516116211227-bbc1107cfae4?auto=format&fit=crop&q=80&w=600',
      page_count: 165,
      file_size: 26800000,
      status: 'approved',
      downloads: 720,
      views: 2450,
      average_rating: 5.0,
      rating_count: 94,
    },
    {
      seller: sellerMap['aman.iitd@notemart.in']._id,
      title: 'Machine Learning & Deep Learning Comprehensive Notes',
      slug: 'machine-learning-deep-learning-notes',
      description: 'Advanced notes covering Supervised Learning (Linear Regression, Logistic, SVM, Decision Trees), Unsupervised Learning (K-Means, PCA), Neural Networks, Backpropagation, CNN, and RNN.',
      subject: 'Machine Learning',
      university: 'IIT Bombay',
      college: 'IIT Bombay CSE',
      course: 'B.Tech AI & ML',
      semester: '6th Semester',
      year: '2026',
      language: 'English',
      tags: ['machine learning', 'ml', 'deep learning', 'neural networks', 'python', 'iit bombay'],
      price: 119,
      is_free: false,
      pdf_path: '/sample-notes/sample.pdf',
      storage_key: 'seed-ml',
      original_filename: 'machine_learning_notes.pdf',
      mime_type: 'application/pdf',
      thumbnail_url: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&q=80&w=600',
      page_count: 180,
      file_size: 29400000,
      status: 'approved',
      downloads: 340,
      views: 1180,
      average_rating: 4.9,
      rating_count: 45,
    },
    {
      seller: sellerMap['ananya.upsc@notemart.in']._id,
      title: 'UPSC Polity M. Laxmikanth Handwritten Summary',
      slug: 'upsc-polity-m-laxmikanth-handwritten-summary',
      description: 'Complete mindmaps and revision tables for Indian Polity based on M. Laxmikanth 7th Edition. Covers Preamble, Fundamental Rights, DPSP, Parliament, Judiciary, Constitutional Bodies, and key landmark Supreme Court judgments.',
      subject: 'Indian Polity',
      university: 'UPSC / IAS',
      college: 'Drishti IAS Toppers Batch',
      course: 'UPSC Civil Services',
      semester: 'Prelims + Mains',
      year: '2026',
      language: 'English',
      tags: ['upsc', 'polity', 'laxmikanth', 'constitution', 'ias', 'prelims', 'mains'],
      price: 149,
      is_free: false,
      pdf_path: '/sample-notes/sample.pdf',
      storage_key: 'seed-upsc-polity',
      original_filename: 'upsc_polity_handwritten.pdf',
      mime_type: 'application/pdf',
      thumbnail_url: 'https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?auto=format&fit=crop&q=80&w=600',
      page_count: 210,
      file_size: 34200000,
      status: 'approved',
      downloads: 630,
      views: 2100,
      average_rating: 5.0,
      rating_count: 82,
    },
    {
      seller: sellerMap['aman.iitd@notemart.in']._id,
      title: 'GATE CSE Previous Year Solved Notes',
      slug: 'gate-cse-previous-year-solved-notes',
      description: 'Detailed topic-wise notes with 10 years of solved GATE CSE questions. Special shortcuts and formula sheets for Theory of Computation, Compiler Design, Discrete Mathematics, and Computer Architecture.',
      subject: 'Computer Science',
      university: 'IIT Kharagpur',
      college: 'GATE Forum',
      course: 'GATE CSE',
      semester: 'GATE Preparation',
      year: '2026',
      language: 'English',
      tags: ['gate', 'gate cse', 'algorithms', 'theory of computation', 'discrete maths'],
      price: 129,
      is_free: false,
      pdf_path: '/sample-notes/sample.pdf',
      storage_key: 'seed-gate-cse',
      original_filename: 'gate_cse_solved_notes.pdf',
      mime_type: 'application/pdf',
      thumbnail_url: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=600',
      page_count: 195,
      file_size: 31000000,
      status: 'approved',
      downloads: 415,
      views: 1530,
      average_rating: 4.9,
      rating_count: 53,
    },
    {
      seller: sellerMap['rohan.aktu.topper@notemart.in']._id,
      title: 'Java Programming Complete Core + Advanced Notes',
      slug: 'java-programming-complete-core-advanced-notes',
      description: 'Complete handwritten guide to Java programming. Covers JVM Architecture, Object-Oriented Principles, Inheritance, Polymorphism, Exception Handling, Collections Framework, Multithreading, Lambdas, and Streams API.',
      subject: 'Java Programming',
      university: 'Dr. A.P.J. Abdul Kalam Technical University (AKTU)',
      college: 'KIET Group of Institutions',
      course: 'B.Tech / BCA',
      semester: '3rd Semester',
      year: '2026',
      language: 'English',
      tags: ['java', 'oops', 'core java', 'collections', 'multithreading', 'aktu', 'bca'],
      price: 49,
      is_free: false,
      pdf_path: '/sample-notes/sample.pdf',
      storage_key: 'seed-java',
      original_filename: 'java_programming_notes.pdf',
      mime_type: 'application/pdf',
      thumbnail_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=600',
      page_count: 128,
      file_size: 19800000,
      status: 'approved',
      downloads: 540,
      views: 1720,
      average_rating: 4.8,
      rating_count: 61,
    },
  ];

  await Note.insertMany(notes);
  console.log(`Successfully seeded ${notes.length} authentic notes into MongoDB!`);
  process.exit(0);
}

seed().catch(err => {
  console.error('Seeding error:', err);
  process.exit(1);
});
